---
name: matlab-language-server
description: Language Server Protocol implementation for the MATLAB language.
homepage: https://github.com/mathworks/MATLAB-language-server
licenses:
  - MIT
languages:
  - Matlab
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/mathworks/MATLAB-language-server@858ee0a62a938e3c92b228860fd6bba36b7a9507
  build:
    run: |
      npm install
      npm run package

bin:
  matlab-language-server: node:out/index.js
